# See https://docs.astral.sh/ruff/rules
[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-async
    "ASYNC",
    # isort
    "I",
    # Flynt `static-join-to-f-string`
    "FLY",
]
